# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: Ace Tracker API
  description: Track CEs and licenses with ACE
  version: "1.0.0"
# the domain of the service
host: ace.medbridge.com
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /v1
produces:
  - application/json
paths:
  /license:
    post:
      summary: Create a new license
      description: |
        This creates a new student license in the License Manager System.
      parameters:
        - name: license
          in: body
          description: serialized JSON license object
          required: true
          type: license
          format: JSON
          
      responses:
        200:
          description: empty
    put:
      summary: Update existing license
      description: |
        This updates an existing license object
      parameters:
        - name: license
          in: body
          description: serialized JSON license object
          required: true
          type: license
          format: JSON
      responses:
        200:
          description empty
    get:
      summary: Get license
      description: |
        This returns a license object by id.
      parameters:
        - name: licenseId
          in: query
          description: Id of the license to return
          required: true
          type: integer
          format: number
      responses:
        200:
          description: A serialized License object
          schema:
            type: JSON
            items:
              $ref: '#/definitions/Product'
        default:
          description: Unexpected error
    delete:
      summary: Delete a license
      description: |
        This deletes a license object by the license Id passed in.
      parameters:
        - name: licenseId
          in: query
          description: Id of the license to delete
          required: true
          type: integer
          format: number
  /activity:
    post:
      summary: Add an activity
      description: |
        This adds an activity, which contains information about the CE Units the         activity will count towards the student's license requirements.
      parameters:
        - name: activity
          in: body
          description: Activity to save
          required: true
          type: Activity
          format: JSON
      responses:
        200:
          description: empty
    put:
      summary: Update an activity
      description: |
        This updates an existing activity.
      parameters:
        - name: activity
          in: body
          description: Activity to save
          required: true
          type: Activity
          format: JSON
      responses:
          200:
            description: empty
    get:
      summary: Get an activity by activity id
      description: |
        This returns an activity object based on the activity Id provided.
      parameters:
        - name: activityId
          in: url
          description: Activity Id
          type: integer
          format: number
      responses:
          200:
            description: empty
          default:
            description: activity not found
    delete:
      summary: Delete an activity
      description: |
        This deletes an existing activity
      parameters:
        - name: activityId
          in: url
          description: Activity Id
          type: integer
          format: number
      responses:
          200:
            description: empty
          default:
            description: activity not found
  /student/{studentId}/activities:
    get:
      summary: Get all student activities
      description: |
        This returns all activities associated with the given student Id
      parameters:
        - name: studentId
          in: url
          description: student Id associated with the activities
          type: integer
          format: number
      responses:
          200:
            description: empty
          default:
            description: activities not found
  /student/{studentId}/check_accreditations/:
    get:
      summary: Get all accreditation information
      description: |
        This returns a summary of all accreditation information associated 
        with a student. For each license associated with a student, this 
        service will return the CEUs remaining, CEUs completed, and CEU 
        Types remaining for the student to maintain the license.
      parameters:
        - name: studentId
          in: url
          description: student Id to retrieve associated license and accreditation records.
          type: integer
          format: number
      responses:
          200:
            description: empty
          default:
            description: no licenses found
  /student/{studentId}/check_accreditations/{licenseId}:
    get:
      summary: Get all accreditation information for one license
      description: |
        This returns only one summary of accreditation information for a 
        given license for a given student. This information includes CEUs 
        remaining, CEUs completed, and CEU Types remaining for the student 
        to maintain the license.
      parameters:
        - name: studentId
          in: url
          description: student Id to retrieve associated license and     accreditation records
          type: integer
          format: number
        - name: licenseId
          in: url
          description: the license Id to retrieve information for
          type: integer
          format: number
      responses:
          200:
            description: empty
          default:
            description: no information found