swagger: '2.0'
info:
  title: Ace Tracker API
  description: Track CEs and licenses with ACE
  version: "1.0.0"
host: ace.medbridge.com
# array of all schemes that your API supports
schemes:
  - https
basePath: /v1
produces:
  - application/json
paths:
  /license:
    post:
      summary: Create a new license
      parameters:
        - name: license
          in: body
          description: JSON serialized license object
          schema:
            $ref: '#/definitions/License'
          required: true
      responses:
        200:
          description: empty
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    put:
      summary: Update existing license
      parameters:
        - name: license
          in: body
          description: JSON serialized license object
          schema:
            $ref: '#/definitions/License'
          required: true
      responses:
        200:
          description: empty
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /license/{licenseId}:
    get:
      summary: Get a license
      parameters:
        - name: licenseId
          in: path
          description: Id of the license to return
          required: true
          type: integer
          format: number
      responses:
        200:
          description: A JSON serialized License object
          schema:
            $ref: '#/definitions/License'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    delete:
      summary: Delete a license
      parameters:
        - name: licenseId
          in: path
          description: Id of the license to delete
          required: true
          type: integer
      responses:
        200:
          description: empty
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /activity:
    post:
      summary: Add an activity
      parameters:
        - name: activity
          in: body
          description: JSON serialized activity object
          schema:
            $ref: '#/definitions/Activity'
          required: true
      responses:
        200:
          description: empty
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    put:
      summary: Update an existing activity
      parameters:
        - name: activity
          in: body
          description: JSON serialized activity object
          schema:
            $ref: '#/definitions/Activity'
          required: true
      responses:
          200:
            description: empty
          default:
            description: Unexpected error
            schema:
              $ref: '#/definitions/Error'
  /activity/{activityId}:
    get:
      summary: Get an JSON serialized activity object by activity id
      parameters:
        - name: activityId
          in: path
          description: Activity Id
          type: integer
      responses:
          200:
            description: JSON serialized activity object
            schema:
              $ref: '#/definitions/License'
          default:
            description: Unexpected error
            schema:
              $ref: '#/definitions/Error'
    delete:
      summary: Delete an activity
      parameters:
        - name: activityId
          in: path
          description: Activity Id
          type: integer
          format: number
      responses:
          200:
            description: empty
          default:
            description: Unexpected error
            schema:
              $ref: '#/definitions/Error'
  /student/{studentId}/licenses:
    get:
      summary: Get all licenses for a given student
      parameters:
        - name: studentId
          in: path
          description: student Id associated with the licenses
          type: integer
      responses:
        200:
          description: A JSON serialized license object array
          schema:
            type: array
            items:
              $ref: '#/definitions/License'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /student/{studentId}/activities:
    get:
      summary: Get all activities for a given student
      parameters:
        - name: studentId
          in: path
          description: student Id associated with the activities
          type: integer
          format: number
      responses:
        200:
          description: A JSON serialized activity object array
          schema:
            type: array
            items:
              $ref: '#/definitions/Activity'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /student/{studentId}/check_accreditations/:
    get:
      summary: Get all accreditation information
      description: |
        This returns a summary of all accreditation information associated 
        with a student. For each license associated with a student, this 
        service will return the CEUs remaining, CEUs completed, and CEU 
        Types remaining for the student to maintain the license.
      parameters:
        - name: studentId
          in: path
          description: student Id to retrieve associated license and accreditation records.
          type: integer
          format: number
      responses:
          200:
            description: A JSON serialized accreditation information object array
            schema:
              type: array
              items:
                $ref: '#/definitions/AccreditationInformation'
          default:
            description: Unexpected error
            schema:
              $ref: '#/definitions/Error'
  /student/{studentId}/check_accreditations/{licenseId}:
    get:
      summary: Get all accreditation information for one license
      description: |
        This returns only one summary of accreditation information for a 
        given license for a given student. This information includes CEUs 
        remaining, CEUs completed, and CEU Types remaining for the student 
        to maintain the license.
      parameters:
        - name: studentId
          in: path
          description: student Id to retrieve associated license and accreditation records
          type: integer
          format: number
        - name: licenseId
          in: path
          description: the license Id to retrieve information for
          type: integer
          format: number
      responses:
          200:
            description: empty
            schema:
              $ref: '#/definitions/AccreditationInformation'
          default:
            description: Unexpected error
            schema:
              $ref: '#/definitions/Error'

definitions:
  License:
    properties:
      id:
        type: integer
      student_id:
        type: integer
      license:
        type: string
      state_id:
        type: integer
      discipline_id:
        type: integer
      expiration:
        type: integer
  Activity:
    properties:
      id:
        type: integer
  Error:
    properties:
      message: 
        type: string
  AccreditationInformation:
    properties:
      licence:
        $ref: '#/definitions/License'
      CEUsAchieved:
        type: integer
      CEUsToGo:
        type: integer
      CEUsToGoByType:
        type: integer